0810
ponopono0322/MergeData pull request #2
Opened 2021-08-10 04:40 UTC by ungan

지난주 깃올리지 못했던 부분 지금 올리겠습니다

2021-08-10 12:03 UTC, ponopono0322 reviewed
코멘트 남기는 것

2021-08-10 12:03 UTC, ponopono0322 requested changes
이것은 확인했다는 request changes 하는 것

2021-08-10 14:49 UTC, ungan reviewed
0810

2021-08-11 08:09 UTC, ungan reviewed
0811

2021-08-11 08:20 UTC, KimchiDelicious approved these changes

2021-08-11 08:29 UTC, merged