0817
ponopono0322/MergeData pull request #4
Opened 2021-08-17 14:54 UTC by ungan

8주차 개발 사항입니다 개발 사항에 대한 부분은 8주차 리포트에 올렸습니다.

2021-08-17 15:38 UTC, KimchiDelicious approved these changes

2021-08-18 07:28 UTC, ponopono0322 requested changes
적어주신 내용들을 확인했으며 오늘 늦은 밤에 패치노트 올리도록 하겠습니다

2021-08-18 21:48 UTC, ungan commented
changes requested 허용해주시면 full request 하도록 하겠습니다

2021-08-19 12:55 UTC, ponopono0322 approved these changes

2021-08-19 12:57 UTC, merged